# Generated by Django 4.2.4 on 2023-09-11 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='clients',
        ),
        migrations.RemoveField(
            model_name='user',
            name='mailings',
        ),
    ]
