# Generated by Django 4.2.4 on 2023-08-23 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailinglog',
            options={'verbose_name': 'Лог рассылки', 'verbose_name_plural': 'Логи рассылок'},
        ),
    ]
