# Generated by Django 4.2.4 on 2023-08-25 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0003_alter_mailing_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='send_time',
            field=models.TimeField(verbose_name='Время рассылки'),
        ),
    ]
