# Generated by Django 4.2.4 on 2023-09-15 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0010_alter_mailing_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='status',
            field=models.CharField(choices=[('created', 'Создана'), ('started', 'Запущена'), ('done', 'Завершена')], default='STATUS_CREATED', max_length=20, verbose_name='Статус рассылки'),
        ),
    ]
